In [113]:
import pandas as pd
import numpy as np
from scipy.stats.stats import pearsonr
import matplotlib.pyplot as plt
from datetime import datetime
from datetime import timedelta
from sklearn import datasets, linear_model
from sklearn.metrics import mean_absolute_error

base = datetime.strptime('20141201', '%Y%m%d') #30-11-2015
date_list = [base + timedelta(minutes=x) for x in range(0, 525600, 15)]
len(date_list)

timeDf = pd.DataFrame({
    'date': date_list
});
# 1. Create a new column day from date
def getDay(x):
    return x.day
timeDf['day'] = timeDf['date'].map(getDay)

# 2. Create a new column month from date
def getMonth(x):
    return x.month
timeDf['month'] = timeDf['date'].map(getMonth)

# 3. Create a new column year from date
def getYear(x):
    return x.year
timeDf['year'] = timeDf['date'].map(getYear)

# 4. Create a new column hour from date
def getHour(x):
    return x.hour
timeDf['hour'] = timeDf['date'].map(getHour)

# 4. Create a new column hour from date
def getWeekDay(x):
    return x.weekday()
timeDf['weekday'] = timeDf['date'].map(getWeekDay)

#timeDf = timeDf[(timeDf['year'] == 2015) & (timeDf['month'] == 11) & (timeDf['day'] == 7)]
timeDf.tail(672)

                     date  day  month  year  hour  weekday
34368 2015-11-24 00:00:00   24     11  2015     0        1
34369 2015-11-24 00:15:00   24     11  2015     0        1
34370 2015-11-24 00:30:00   24     11  2015     0        1
34371 2015-11-24 00:45:00   24     11  2015     0        1
34372 2015-11-24 01:00:00   24     11  2015     1        1
34373 2015-11-24 01:15:00   24     11  2015     1        1
34374 2015-11-24 01:30:00   24     11  2015     1        1
34375 2015-11-24 01:45:00   24     11  2015     1        1
34376 2015-11-24 02:00:00   24     11  2015     2        1
34377 2015-11-24 02:15:00   24     11  2015     2        1
34378 2015-11-24 02:30:00   24     11  2015     2        1
34379 2015-11-24 02:45:00   24     11  2015     2        1
34380 2015-11-24 03:00:00   24     11  2015     3        1
34381 2015-11-24 03:15:00   24     11  2015     3        1
34382 2015-11-24 03:30:00   24     11  2015     3        1
34383 2015-11-24 03:45:00   24     11  2015     3        1
34384 2015-11-24 04:00:00   24     11  2015     4        1
34385 2015-11-24 04:15:00   24     11  2015     4        1
34386 2015-11-24 04:30:00   24     11  2015     4        1
34387 2015-11-24 04:45:00   24     11  2015     4        1
34388 2015-11-24 05:00:00   24     11  2015     5        1
34389 2015-11-24 05:15:00   24     11  2015     5        1
34390 2015-11-24 05:30:00   24     11  2015     5        1
34391 2015-11-24 05:45:00   24     11  2015     5        1
34392 2015-11-24 06:00:00   24     11  2015     6        1
34393 2015-11-24 06:15:00   24     11  2015     6        1
34394 2015-11-24 06:30:00   24     11  2015     6        1
34395 2015-11-24 06:45:00   24     11  2015     6        1
34396 2015-11-24 07:00:00   24     11  2015     7        1
34397 2015-11-24 07:15:00   24     11  2015     7        1
...                   ...  ...    ...   ...   ...      ...
35010 2015-11-30 16:30:00   30     11  2015    16        0
35011 2015-11-30 16:45:00   30     11  2015    16        0
35012 2015-11-30 17:00:00   30     11  2015    17        0
35013 2015-11-30 17:15:00   30     11  2015    17        0
35014 2015-11-30 17:30:00   30     11  2015    17        0
35015 2015-11-30 17:45:00   30     11  2015    17        0
35016 2015-11-30 18:00:00   30     11  2015    18        0
35017 2015-11-30 18:15:00   30     11  2015    18        0
35018 2015-11-30 18:30:00   30     11  2015    18        0
35019 2015-11-30 18:45:00   30     11  2015    18        0
35020 2015-11-30 19:00:00   30     11  2015    19        0
35021 2015-11-30 19:15:00   30     11  2015    19        0
35022 2015-11-30 19:30:00   30     11  2015    19        0
35023 2015-11-30 19:45:00   30     11  2015    19        0
35024 2015-11-30 20:00:00   30     11  2015    20        0
35025 2015-11-30 20:15:00   30     11  2015    20        0
35026 2015-11-30 20:30:00   30     11  2015    20        0
35027 2015-11-30 20:45:00   30     11  2015    20        0
35028 2015-11-30 21:00:00   30     11  2015    21        0
35029 2015-11-30 21:15:00   30     11  2015    21        0
35030 2015-11-30 21:30:00   30     11  2015    21        0
35031 2015-11-30 21:45:00   30     11  2015    21        0
35032 2015-11-30 22:00:00   30     11  2015    22        0
35033 2015-11-30 22:15:00   30     11  2015    22        0
35034 2015-11-30 22:30:00   30     11  2015    22        0
35035 2015-11-30 22:45:00   30     11  2015    22        0
35036 2015-11-30 23:00:00   30     11  2015    23        0
35037 2015-11-30 23:15:00   30     11  2015    23        0
35038 2015-11-30 23:30:00   30     11  2015    23        0
35039 2015-11-30 23:45:00   30     11  2015    23        0

[672 rows x 6 columns]

In [114]:
def predictDemandFor24Hours(houseNo):
    
    fileName = "Home"+str(houseNo)+"_yr1.csv"
    df = pd.read_csv(fileName,sep=",", names = ["demand"])
    data = pd.concat([df, timeDf], axis=1)

    #One Hot Encoding for categorical features
    dataX = pd.get_dummies(data, columns=["day", "month", "year", "hour",  "weekday"])
    dataX = dataX.drop(columns=['demand', 'date'])
    dataY = pd.DataFrame({
        'demand': data.demand
    })

    trainX = dataX[0:32159]  #34944
    trainY = dataY[0:32159]

    testX = dataX[32160:32840]
    testY = dataY[32160:32840] 

    #print("******** Train Data X Shape:", trainX.shape)
    #print("******** Train Data Y Shape:", trainY.shape)
    #print("******** Test Data X Shape:", testX.shape)
    #print("******** Test Data Y Shape:", testY.shape)
    
    return data, trainX, trainY, testX, testY

# DATA ANALYSIS

In [115]:
# Data Analysis on the original data

def dataAnalysis(data):
    
    groupby_month = data.groupby(['month']).mean()
    plt.plot(groupby_month.demand, color='blue')
    plt.xlabel('Month')
    plt.ylabel('Average Electricity Demand')
    plt.show()

    groupby_weekday = data.groupby(['weekday']).mean()
    plt.plot(groupby_weekday.demand, color='gray')
    plt.xlabel('Weekday')
    plt.ylabel('Average Electricity Demand')
    plt.show()

    groupby_hour = data.groupby(['hour']).mean()
    plt.plot(groupby_hour.demand, color='red')
    plt.xlabel('Hour')
    plt.ylabel('Average Electricity Demand')
    plt.show()

    groupby_day = data.groupby(['day']).mean()
    plt.plot(groupby_day.demand, color='green')
    plt.xlabel('Day')
    plt.ylabel('Average Electricity Demand')
    plt.show()

# NAIVE APPROACH

In [116]:
# Naive Method

def naiveMethod(modelList, maeList, house):
    demandArray = np.asarray(trainY.demand)
    y_predicted = testY.copy()
    y_predicted['baseline'] = demandArray[len(demandArray)-1]

    testingError = mean_absolute_error(testY.demand, y_predicted.baseline)
    y_predicted.baseline.to_csv("House_"+str(house)+"_Baseline.csv", index=False)
    #print(testingError)
    modelList.append("Naive");
    maeList.append(testingError);

# MEAN APPROACH

In [117]:
# Average Approach
def meanApproach(modelList, maeList, house):
    y_predicted = testY.copy()
    y_predicted['average'] = trainY.demand.mean()
    testingError = mean_absolute_error(testY.demand, y_predicted.average)
    y_predicted.average.to_csv("House_"+str(house)+"_MeanApproach.csv", index=False)
    #print(testingError)
    modelList.append("Average");
    maeList.append(testingError);

# ROLLING AVERAGE APPROACH

In [145]:
# Rolling Average Approach
def rollingAverage(modelList, maeList, trainY, testY, house):
    
    temp1 = trainY[-60:-1]
    temp1.reset_index()
    

    print(temp.demand)
    
    
    y_predicted = pd.DataFrame({})
    temp['movingAverage'] = temp.demand.rolling(59).mean()
    print(temp.movingAverage)
    testingError = mean_absolute_error(testY.demand, temp.movingAverage)
    y_predicted.movingAverage.to_csv("House_"+str(house)+"_RollingAverage.csv", index=False)
    print("Testing Error", testingError)
    modelList.append("Moving Average");
    maeList.append(testingError);

In [156]:
from sklearn.svm import SVR
def SV(modelList, maeList, trainX, trainY, testX, testY, house):
    
    scaler = preprocessing.StandardScaler().fit(trainX)
    trainX = scaler.transform(trainX)
    
    scaler = preprocessing.StandardScaler().fit(testX)
    testX = scaler.transform(testX)
    
    clf = SVR(gamma='scale', C=1.0, epsilon=0.2)
    model = clf.fit(trainX, trainY.values.ravel()) 
    trainMae = mean_absolute_error(trainY, clf.predict(trainX))
    print("Train MAE: ", trainMae)
    
    # Testing
    y_predicted = clf.predict(testX)
    
    df = pd.DataFrame({
        "prediction": y_predicted
    })
    #df.prediction.to_csv("House_"+str(house)+"_LinearRegression.csv", index=False)
    testMae =  mean_absolute_error(testY, y_predicted)
    print("Test MAE: ", testMae)

    modelList.append("SV Regression");
    maeList.append(testMae);

# SIMPLE LINEAR REGRESSION

In [164]:
# Simple Linear Regression

from sklearn import linear_model
from sklearn import preprocessing

def linearRegression(modelList, maeList, trainX, trainY, testX, testY, house):
    # Preprocessing
    scaler = preprocessing.StandardScaler().fit(trainX)
    trainX = scaler.transform(trainX)

    scaler = preprocessing.StandardScaler().fit(testX)
    testX = scaler.transform(testX)

    # Training
    regr = linear_model.Ridge()
    model = regr.fit(trainX, trainY.values.ravel())
    trainMae = mean_absolute_error(trainY, regr.predict(trainX))
    print("Train MAE: ", trainMae)

    # Testing
    y_predicted = regr.predict(testX)
    
    df = pd.DataFrame({
        "prediction": y_predicted
    })
    df.prediction.to_csv("House_"+str(house)+"_RidgeRegression.csv", index=False)
    testMae =  mean_absolute_error(testY, y_predicted)
    print("Test MAE: ", testMae)

    modelList.append("Ridge Regression");
    maeList.append(testMae);

# RANDOM FOREST

In [120]:
#Random Forest
from sklearn.ensemble import RandomForestRegressor

def randomForest(modelList, maeList, trainX, trainY, testX, testY, house):
    
    print("Random Forest Regressor");
    # Training
    regr = RandomForestRegressor()
    model = regr.fit(trainX, trainY.values.ravel())
    trainMae = mean_absolute_error(trainY, regr.predict(trainX))

    print("Train MAE: ", trainMae)

    # Testing
    y_predicted = regr.predict(testX)
    df = pd.DataFrame({
        "prediction": y_predicted
    })
    
    print(y_predicted);
    df.prediction.to_csv("House_"+str(house)+"_RandomForest.csv", index=False)
    testMae =  mean_absolute_error(testY, y_predicted)
    #print("Test MAE: ", testMae)

    modelList.append("Random Forest");
    maeList.append(testMae);

# SARIMA

In [121]:
# SARIMA
import statsmodels.api as sm

def sarima(modelList, maeList, trainY, testY, house):
    
    fit1 = sm.tsa.statespace.SARIMAX(trainY.demand).fit()
    y_predicted = fit1.predict(start=34945, end=35040, dynamic=True)
    y_predicted.to_csv("House_"+str(house)+"_Sarima.csv", index=False)
    testingError = mean_absolute_error(testY.demand, y_predicted)
    #print(testingError)
    modelList.append("Arima");
    maeList.append(testingError);

# FINAL RESULT

In [158]:
modelList = []
maeList = []
house = 4
data, trainX, trainY, testX, testY = predictDemandFor24Hours(house)
SV(modelList, maeList, trainX, trainY, testX, testY, house)

TypeError: must be real number, not str

In [165]:
results = pd.DataFrame({
        'Approach': ["Naive", "Mean", "Rolling Average", "Linear Regression", "Random Forest"]
        })
for house in range(1,11):
    modelList = []
    maeList = []
    
    data, trainX, trainY, testX, testY = predictDemandFor24Hours(house)
    #dataAnalysis(data)
    #naiveMethod(modelList, maeList, house)
    #meanApproach(modelList, maeList, house)
    #rollingAverage(modelList, maeList,trainY, testY, house)
    linearRegression(modelList, maeList, trainX, trainY, testX, testY, house)
    #randomForest(modelList, maeList, trainX, trainY, testX, testY, house)
    #sarima(modelList, maeList, trainY, testY, house)
    
    houseNo = "house"+str(house)
    #results[houseNo] = maeList
    
#results

Train MAE:  0.7429666488323223
Test MAE:  0.7628830187665839
Train MAE:  0.8524480989469203
Test MAE:  1.0171628078336223
Train MAE:  0.7025870915109155
Test MAE:  0.8466682431932963
Train MAE:  0.6163162653814932
Test MAE:  0.8212716396003978
Train MAE:  0.8164479863679118
Test MAE:  0.9780769525476551
Train MAE:  0.7476662773379293
Test MAE:  0.9596273533911004
Train MAE:  0.8199955571989531
Test MAE:  0.964489417238299
Train MAE:  0.9409587369663412
Test MAE:  0.9970264005599163
Train MAE:  0.5535376174647516
Test MAE:  0.629615603882038
Train MAE:  0.6417403123469927
Test MAE:  0.7711067669437983

In [96]:
modelList = []
maeList = []
house = 4
data, trainX, trainY, testX, testY = predictDemandFor24Hours(house)
randomForest(modelList, maeList, trainX, trainY, testX, testY, house)

Random Forest Regressor
Train MAE:  0.39067176356083455
[0.43776218 0.43776218 0.43776218 0.43776218 0.3661119  0.3661119
 0.3661119  0.3661119  0.34679199 0.34679199 0.34679199 0.34679199
 0.57305011 0.57305011 0.57305011 0.57305011 0.29146077 0.29146077
 0.29146077 0.29146077 0.37572835 0.37572835 0.37572835 0.37572835
 0.3573926  0.3573926  0.3573926  0.3573926  0.82761545 0.82761545
 0.82761545 0.82761545 1.200245   1.200245   1.200245   1.200245
 0.88199504 0.88199504 0.88199504 0.88199504 1.00022287 1.00022287
 1.00022287 1.00022287 0.24672082 0.24672082 0.24672082 0.24672082
 0.34421619 0.34421619 0.34421619 0.34421619 0.73009928 0.73009928
 0.73009928 0.73009928 1.06723482 1.06723482 1.06723482 1.06723482
 0.64353544 0.64353544 0.64353544 0.64353544 0.98343326 0.98343326
 0.98343326 0.98343326 0.91884253 0.91884253 0.91884253 0.91884253
 1.00995325 1.00995325 1.00995325 1.00995325 0.82278925 0.82278925
 0.82278925 0.82278925 1.0283356  1.0283356  1.0283356  1.0283356
 0.44381557 0.44381557 0.44381557 0.44381557 0.49641341 0.49641341
 0.49641341 0.49641341 0.9637307  0.9637307  0.9637307  0.9637307
 0.9177597  0.9177597  0.9177597  0.9177597  0.60077727 0.60077727
 0.60077727 0.60077727 0.45482913 0.45482913 0.45482913 0.45482913
 0.47421623 0.47421623 0.47421623 0.47421623 0.47576711 0.47576711
 0.47576711 0.47576711 0.60314595 0.60314595 0.60314595 0.60314595
 0.49895985 0.49895985 0.49895985 0.49895985 1.16940763 1.16940763
 1.16940763 1.16940763 0.43322866 0.43322866 0.43322866 0.43322866
 1.82221469 1.82221469 1.82221469 1.82221469 1.56261813 1.56261813
 1.56261813 1.56261813 1.12401022 1.12401022 1.12401022 1.12401022
 1.5094505  1.5094505  1.5094505  1.5094505  1.86520111 1.86520111
 1.86520111 1.86520111 1.58484904 1.58484904 1.58484904 1.58484904
 1.3925455  1.3925455  1.3925455  1.3925455  1.10372837 1.10372837
 1.10372837 1.10372837 0.66557106 0.66557106 0.66557106 0.66557106
 0.54584488 0.54584488 0.54584488 0.54584488 0.46533694 0.46533694
 0.46533694 0.46533694 0.98784833 0.98784833 0.98784833 0.98784833
 0.63042035 0.63042035 0.63042035 0.63042035 0.39456999 0.39456999
 0.39456999 0.39456999 0.89036625 0.89036625 0.89036625 0.89036625
 0.67322472 0.67322472 0.67322472 0.67322472 0.85356033 0.85356033
 0.85356033 0.85356033 0.60126557 0.60126557 0.60126557 0.60126557
 0.66461342 0.66461342 0.66461342 0.66461342 0.71669039 0.71669039
 0.71669039 0.71669039 0.76804671 0.76804671 0.76804671 0.76804671
 1.52316907 1.52316907 1.52316907 1.52316907 5.284688   5.284688
 5.284688   5.284688   0.71024372 0.71024372 0.71024372 0.71024372
 0.8940161  0.8940161  0.8940161  0.8940161  2.11070945 2.11070945
 2.11070945 2.11070945 0.64138445 0.64138445 0.64138445 0.64138445
 1.08271169 1.08271169 1.08271169 1.08271169 0.56165382 0.56165382
 0.56165382 0.56165382 0.16025545 0.16025545 0.16025545 0.16025545
 0.48240202 0.48240202 0.48240202 0.48240202 0.43571337 0.43571337
 0.43571337 0.43571337 0.68130052 0.68130052 0.68130052 0.68130052
 0.7652978  0.7652978  0.7652978  0.7652978  0.8951444  0.8951444
 0.8951444  0.8951444  0.61922806 0.61922806 0.61922806 0.61922806
 0.44787085 0.44787085 0.44787085 0.44787085 0.379355   0.379355
 0.379355   0.379355   0.57848053 0.57848053 0.57848053 0.57848053
 0.45260583 0.45260583 0.45260583 0.45260583 0.50776152 0.50776152
 0.50776152 0.50776152 0.52458602 0.52458602 0.52458602 0.52458602
 0.46222957 0.46222957 0.46222957 0.46222957 0.41803021 0.41803021
 0.41803021 0.41803021 0.51417497 0.51417497 0.51417497 0.51417497
 0.49292253 0.49292253 0.49292253 0.49292253 0.44018624 0.44018624
 0.44018624 0.44018624 0.97443734 0.97443734 0.97443734 0.97443734
 1.04056079 1.04056079 1.04056079 1.04056079 1.3945659  1.3945659
 1.3945659  1.3945659  0.73170274 0.73170274 0.73170274 0.73170274
 0.61599732 0.61599732 0.61599732 0.61599732 0.48888336 0.48888336
 0.48888336 0.48888336 0.52498603 0.52498603 0.52498603 0.52498603
 0.32717704 0.32717704 0.32717704 0.32717704 0.39166313 0.39166313
 0.39166313 0.39166313 0.616447   0.616447   0.616447   0.616447
 0.51423863 0.51423863 0.51423863 0.51423863 0.80874899 0.80874899
 0.80874899 0.80874899 0.94632526 0.94632526 0.94632526 0.94632526
 1.28036936 1.28036936 1.28036936 1.28036936 0.79228652 0.79228652
 0.79228652 0.79228652 0.4361433  0.4361433  0.4361433  0.4361433
 0.29843738 0.29843738 0.29843738 0.29843738 0.43907947 0.43907947
 0.43907947 0.43907947 0.3723702  0.3723702  0.3723702  0.3723702
 0.360037   0.360037   0.360037   0.360037   0.37138255 0.37138255
 0.37138255 0.37138255 0.3410575  0.3410575  0.3410575  0.3410575
 0.35668096 0.35668096 0.35668096 0.35668096 0.45844075 0.45844075
 0.45844075 0.45844075 0.69593886 0.69593886 0.69593886 0.69593886
 2.64389162 2.64389162 2.64389162 2.64389162 1.27194248 1.27194248
 1.27194248 1.27194248 0.79180987 0.79180987 0.79180987 0.79180987
 0.76245691 0.76245691 0.76245691 0.76245691 0.52112099 0.52112099
 0.52112099 0.52112099 0.48853044 0.48853044 0.48853044 0.48853044
 0.2757191  0.2757191  0.2757191  0.2757191  0.51146088 0.51146088
 0.51146088 0.51146088 0.7088683  0.7088683  0.7088683  0.7088683
 0.81243227 0.81243227 0.81243227 0.81243227 1.11236001 1.11236001
 1.11236001 1.11236001 1.02737346 1.02737346 1.02737346 1.02737346
 0.63440988 0.63440988 0.63440988 0.63440988 0.58539726 0.58539726
 0.58539726 0.58539726 0.63935321 0.63935321 0.63935321 0.63935321
 0.36768549 0.36768549 0.36768549 0.36768549 0.3264467  0.3264467
 0.3264467  0.3264467  0.35512168 0.35512168 0.35512168 0.35512168
 0.36111165 0.36111165 0.36111165 0.36111165 0.3102808  0.3102808
 0.3102808  0.3102808  0.36017798 0.36017798 0.36017798 0.36017798
 0.47098303 0.47098303 0.47098303 0.47098303 0.4357403  0.4357403
 0.4357403  0.4357403  0.83174157 0.83174157 0.83174157 0.83174157
 1.83078218 1.83078218 1.83078218 1.83078218 1.8340252  1.8340252
 1.8340252  1.8340252  0.88091415 0.88091415 0.88091415 0.88091415
 0.44208474 0.44208474 0.44208474 0.44208474 0.9871722  0.9871722
 0.9871722  0.9871722  0.88840532 0.88840532 0.88840532 0.88840532
 0.54846562 0.54846562 0.54846562 0.54846562 0.65950738 0.65950738
 0.65950738 0.65950738 1.26413042 1.26413042 1.26413042 1.26413042
 0.85260857 0.85260857 0.85260857 0.85260857 0.45037764 0.45037764
 0.45037764 0.45037764 0.5785494  0.5785494  0.5785494  0.5785494
 0.56860438 0.56860438 0.56860438 0.56860438 0.50113834 0.50113834
 0.50113834 0.50113834 0.48769569 0.48769569 0.48769569 0.48769569
 0.37321122 0.37321122 0.37321122 0.37321122 0.39268594 0.39268594
 0.39268594 0.39268594 0.54850111 0.54850111 0.54850111 0.54850111
 0.56845848 0.56845848 0.56845848 0.56845848 0.71808918 0.71808918
 0.71808918 0.71808918 0.78267715 0.78267715 0.78267715 0.78267715
 0.77265936 0.77265936 0.77265936 0.77265936 0.37618178 0.37618178
 0.37618178 0.37618178 0.61881768 0.61881768 0.61881768 0.61881768
 0.35609622 0.35609622 0.35609622 0.35609622 0.89742886 0.89742886
 0.89742886 0.89742886 0.48625262 0.48625262 0.48625262 0.48625262
 0.28652313 0.28652313 0.28652313 0.28652313 1.10966816 1.10966816
 1.10966816 1.10966816 1.25891521 1.25891521 1.25891521 1.25891521
 0.3740303  0.3740303  0.3740303  0.3740303  0.47046398 0.47046398
 0.47046398 0.47046398 0.5514738  0.5514738  0.5514738  0.5514738
 0.81916717 0.81916717 0.81916717 0.81916717 0.48574959 0.48574959
 0.48574959 0.48574959 0.80483175 0.80483175 0.80483175 0.80483175
 0.93542335 0.93542335 0.93542335 0.93542335 0.74180012 0.74180012
 0.74180012 0.74180012 0.25895157 0.25895157 0.25895157 0.25895157]